name: flutkit
description: A new Flutter project.


# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 6.1.0
versionCode: 4

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutx:
    path: flutx


  # Base Dependencies
  cupertino_icons: ^1.0.3
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  google_fonts: ^2.0.0
  image_picker: ^0.8.6
  # image_cropper: ^3.0.0
  image_pickers: ^2.0.0+6
  get:
  get_storage: ^2.0.3
  art_sweetalert: ^0.0.5
  carousel_slider: ^4.1.1
  carousel_indicator: ^1.0.6
  dio: ^4.0.6
  dio_http_cache: ^0.3.0
  flutter_share: any
  contactus: ^1.2.0






  # Icons
  material_design_icons_flutter: ^6.0.7096
  flutter_feather_icons: ^2.0.0+1

  #(Syncfusion Flutter packages - Charts, Calendar, ETC.)
  syncfusion_flutter_core: ^20.3.59
  syncfusion_flutter_calendar: ^20.3.59
  syncfusion_flutter_datepicker: ^20.3.59
  syncfusion_flutter_sliders: ^20.3.59
  syncfusion_flutter_charts: ^20.3.59
  syncfusion_flutter_gauges: ^20.3.59

  # Other
  google_maps_flutter: ^2.0.3
  shimmer: ^2.0.0
  url_launcher: ^6.0.3
  intl: ^0.17.0
  rive: ^0.9.1
  flare_flutter: ^3.0.2
  flutter_intro: ^3.0.2
  decorated_dropdownbutton: ^0.0.3
  flutter_easyloading: ^3.0.5
  pin_code_fields: ^7.4.0
  data_connection_checker: ^0.3.4
  connectivity: ^3.0.6
  flutter_windowmanager: ^0.2.0
  flutter_cached_pdfview: ^0.4.1
  path_provider: ^2.0.2
  percent_indicator: ^4.0.1
  video_player: ^2.5.1
  # just_audio: ^0.9.31
  audioplayers: ^0.20.1
  badges: ^2.0.3
  firebase_messaging: ^14.1.4
  flutter_local_notifications: ^12.0.4
  firebase_auth: ^4.2.5
  permission_handler: ^10.2.0
  file_picker: ^4.6.1
  flutter_downloader: ^1.10.1+2
  cached_network_image: ^3.2.3
  
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/filesLogo/

    #Profiles
    - assets/images/profile/

    - assets/icons/otp.gif

    #Chat
    - assets/images/chat/

    ##Estate (Material Design 3)
    - lib/src/data/
    #Languages
    - assets/lang/
    #Icons
    - assets/icons/


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
  
